remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # 
gem "github-pages", group: :jekyll_plugins

title: [Oasis Discord]
tagline: [Link website for the Discord server]
description: [This is a website to provide access to our Discord Community server]
